### ISSUE TITLE
Image remains black

### ISSUE THREAD

**Issue by kameamea** [csantosbh/gdb-imagewatch#1]
Everything seems to work (I can select variables, see their min/max values), but the image are all black, no matter whether RGB or gray, preview/symbol column or main window). Any idea? I had to use qt5 to get ImageWatch compiled BTW, despite the README which says qt4, but I guess this is not the reason. I have no separate GPU, just a skylake i5 CPU graphics.

**Comment by csantosbh** [comment]
There's a way to test the imagewatch on the console. Go to the installation folder and run the following command:

`$ python3 gdb-imagewatch.py --test`

If you perform this step, could you copy the messages that are displayed on the console here?

**Comment by kameamea** [comment]
QMetaObject::connectSlotsByName: No matching signal for on_symbol_selected()
QMetaObject::connectSlotsByName: No matching signal for on_symbol_completed(QString)
Failed to compile shadertype: Vertex Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Fragment Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Vertex Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Fragment Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Vertex Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Fragment Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Vertex Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Failed to compile shadertype: Fragment Shader
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "gdb-imagewatch.py", line 65, in plot_variable_cbk
    gdb.post_event(MainThreadPlotVariableRunner(variable))
NameError: name 'gdb' is not defined

**Comment by csantosbh** [comment]
Thanks. I was suspecting about the version of OpenGL supported by your machine. I'll see if I can make the imagewatch work with an older OpenGL version.

**Comment by csantosbh** [comment]
@kameamea I have pushed a hotfix that converts the shaders to GLSL 120. It's available in the branch `glsl120_hotfix`. You can grab it by running:

    git pull
    git checkout glsl120_hotfix

After that, you would need to go to the installation folder and re-run `make install`. Could you test this patch, please?

**Comment by kameamea** [comment]
works like a charm. Thanks a lot for this helpful tool

**Comment by csantosbh** [comment]
No problem. I'm merging the patch into the branch `master` and deleting the branch `glsl120_hotfix`.
Thanks for reporting this issue.
