### ISSUE TITLE
Feature request: create a "go to pixel" window

### ISSUE THREAD

**Issue by brunoalr** [csantosbh/gdb-imagewatch#19]
Feature request: create a "go to pixel" window

**Comment by csantosbh** [comment]
Thanks for the suggestion!

I'm considering to have this on v1.2. Would you like to discuss the possibilities for how this would work after implemented?

These are the possibilities that I currently have in mind:

1. Vim-like behavior to the symbol search bar
    - In the search bar, the user could type ":" followed by a pixel localizer
    - If the user types ":Y" (Y being a number), then the viewer will zoom to the N row, keeping at the current row, with a zoom large enough to view the pixel values
    - If the user types ":Y,X", the the viewer will zoom to the pixel at <x, y>, as below
2. Additional terminal for commands
    - If the user presses ":" (or any other configurable shortcut) at any moment, then a go-to-pixel bar could appear at the bottom of the screen
    - The behaviour could be the same as the vim-like search bar (without the need for the additional ":" keystroke)
    - Or the go-to-pixel bar could consist of two input fields, that the user could alternate between by using the tab key (or just using the mouse)
3. Smarter vim-like behavior to symbol search bar
    - Same as option (1), but requiring ":x X" or ":y Y" for going to an arbitrary column or row, or ": X,Y" for going to an arbitrary pixel

What do you think? Feel free to suggest other ideas.

**Comment by brunoalr** [comment]
@csantosbh thanks for the reply!

I believe a feature based on option 2.3 (two input fields) would the most user-friendly option. A small tweak I suggest is to center the selected pixel in the viewer.

Also two buttons named something "Center collumn" and "Center row" would be nice to be add so that an user can input "row: 1500, column: 0", then click in "Center column" and the viewer will be centered at half the of the row 1500.

**Comment by csantosbh** [comment]
I've made a draft in terms of interface for an initial experiment with usability and looks. Here is a screenshot:

![screenshot from 2017-11-03 00-11-42](https://user-images.githubusercontent.com/1847919/32358297-03bde77c-c02c-11e7-82b6-cadd38454c8e.png)

The idea is that the inputs at the lower right corner will show up when the user presses a go-to shortcut (initial suggestion: ctrl+l). After typing the desired location, the user can press <enter>, which will close the inputs and make the viewer zoom into the specified location. The zoom will be large enough for the pixel values to become visible.

What do you think about it @brunoalr?

**Comment by brunoalr** [comment]
I think it looks awesome :D

**Comment by csantosbh** [comment]
The first version of this feature is now available in the branch v1.2-dev. It has been tested with normal and rotated buffers; nevertheless if there are any bugs or improvements that can be done to this initial version, please let me know.

**Comment by brunoalr** [comment]
Awesome! I'm testing it right now, and I have some minor UX-wise suggestions: `ctrl+L` is nice, but I think a visible button would be good for the average user as well. Also, it would nice to have `x` and `y` labels in the input forms.

**Comment by csantosbh** [comment]
Sure!

By the way, using this functionality today I felt like it would have been more useful if it didn't force zooming into the screen. The use case is when manually aligning buffers: When the zoom automatically changes, it is harder to manually align the buffers; if however the zoom was kept intact, I could zoom into the desired pixel if I wanted to. So I'm seriously considering to change the automatic zoom behavior.

**Comment by csantosbh** [comment]
@brunoalr  Any ideas for an icon for this feature? Here are some options:

http://fontello.com/

I'm currently between the "location" and the "target" icons (look for these terms in the search bar).

**Comment by brunoalr** [comment]
I liked the Font Awesome search icon, but this choice is up to you really :P

**Comment by csantosbh** [comment]
Although I like the search icon, I think its meaning would better match the symbol search input. I've added a button with the  "location" icon, and the "x" and "y" labels on the goto inputs as well.

Could you please take a look at it? If all works fine, we can close the issue.

**Comment by csantosbh** [comment]
Closing as the solution seems stable enough.
