### ISSUE TITLE
no interaction possible in ubuntu 16.04.02

### ISSUE THREAD

**Issue by kameamea** [csantosbh/gdb-imagewatch#2]
I upgraded to ubuntu 16.04.02 and now gdb-imagewatch opens but doesn't allow any kind of interaction, even closing it's window doesn't work ("application is not responding" or something like that is the error).
It makes no difference whether I use the (once successful) build from my earlier ubuntu or a newly compiled one.

This is the output of the test (incl. killing it with Ctrl-C):

python3 gdb-imagewatch.py --test

QMetaObject::connectSlotsByName: No matching signal for on_symbol_selected()
QMetaObject::connectSlotsByName: No matching signal for on_symbol_completed(QString)
^CTraceback (most recent call last):
  File "gdb-imagewatch.py", line 120, in <module>
    time.sleep(0.5)
KeyboardInterrupt
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by kameamea** [comment]
twice I could use the "triangle" button and got a response (but after that no response whatsoever), so the process seems not to be completely dead, perhaps more like in an endless loop with no time slot for user interactions?

**Comment by csantosbh** [comment]
Thanks for the bug report, @kameamea. Unfortunately I'll only have access to my personal computer (where I have Ubuntu 16.04.1 and can upgrade to .2) in the next month, so I won't be able to reproduce this issue until then. In the mean time, did you try to upgrade the gdb-imagewatch to the latest version from Feb 14? I recall having some issues with Ubuntu 16.04 and had to make some changes to the gdb-imagewatch.py script.

**Comment by kameamea** [comment]
I upgraded to the latest version of gdb-imagewatch and now everythings works fine again.
