### ISSUE TITLE
Remove as many external dependencies as possible

### ISSUE THREAD

**Issue by csantosbh** [csantosbh/gdb-imagewatch#26]
The following external dependencies can be replaced by a Qt functionality:

* ~~GLEW, can be replaced by QOpenGLExtraFunctions~~
* ~~FreeType, might be replaceable by QFont+QPixmap+QPainter~~

The following external dependencies may be embedded into our repo as a submodule:

* ~~Eigen~~
* ~~pysigset~~

Other external dependencies that should be removed:
* ~~numpy (only needed for the test window, there must be some way to generate the buffers without it)~~
* ~~texinfo~~

**Comment by brunoalr** [comment]
Hell yeah!

**Comment by csantosbh** [comment]
Just integrated the Eigen source code into the repo. Sadly, there is no official git mirror for the Eigen project, therefore I had to perform a full copy of the Eigen library (which has about 5MB uncompressed).

**Comment by csantosbh** [comment]
Just integrated the Eigen source code as a submodule. Since there is no official git mirror for the Eigen project, I created a fork of my own.
I'm thinking about doing the same with pysigset, which will remove two dependencies from the installation procedure (pip3 and pysigset itself).
