### ISSUE TITLE
Feature Request: add keyboard hotkeys to move the bufers

### ISSUE THREAD

**Issue by brunoalr** [csantosbh/gdb-imagewatch#29]
In the same spirit of the `ctrl + +` and `ctrl + -` hotkeys, I think it would also be nice for us to have hotkeys to move the buffers instead of relying on mouse actions only. A first suggestion would be `ctrl` + arrow keys.

**Comment by csantosbh** [comment]
Nice one!

The implementation is available in 4ef11a8. Could you test it please?

**Comment by csantosbh** [comment]
I just realized that rotated buffers are not properly taken care of. I'll fix this issue later.
