### ISSUE TITLE
Project ERROR: python3 development package not found

### ISSUE THREAD

**Issue by kameamea** [csantosbh/gdb-imagewatch#39]
I tried installing gdb-imagewatch on two different machines. Both are ubuntu 16.04.04

No matter which way I try (manual or by the configure_ubuntu_16.sh script) I get this error on qmake:

Project ERROR: python3 development package not found

This is the output from python3 install:

sudo apt-get install libpython3-dev
libpython3-dev is already the newest version (3.5.1-3).

**Comment by kameamea** [comment]
on one of the two machines I suceeded to install after a reboot. After that reboot libpython3-dev wasn't visible by apt anymore, so I could install it again, and then everything worked.

On the other machine (which I can't reboot) nothing helped so far, neither
apt-get install --reinstall  libpython3-dev
nor apt-get remove 

So this all seems to be a apt related problem on ubuntu 16.04.04

**Comment by csantosbh** [comment]
Hi kameamea, thanks again for your collaboration!
After installing libpython3-dev, did you try cleaning your build folder and rebuilding from scratch?

In any case, I have a feeling I've had this before when trying to build on a VM for testing. I'll check that later and will let you know if I had to install any other packages.

**Comment by csantosbh** [comment]
Hello @kameamea! Sorry for the late reply, the past few days were quite rough for me.
I've reinstalled an Ubuntu 16.04 on a VM and confirmed the issue. As I suspected, I've seen this issue before. To fix it, you need to install the package `python3-dev` (without the "lib"). I'll be updating the installation instructions and the script as well to reflect this.

Thank you again!

**Comment by midddle** [comment]
I tried a new (minimal) Ubuntu 18.04 in VM, got the same problem even after installing _python3-lib_, for me installing _pkg-config_ solved the problem.

**Comment by brunoalr** [comment]
@midddle thanks for documenting this solution for Ubuntu 18.04! I'm setting up a CI for the project and just encountered the same issue.
