### ISSUE TITLE
visual code

### ISSUE THREAD

**Issue by ghost** [csantosbh/gdb-imagewatch#44]
Is this gdb-imagewatch available as [Extension for Visual Code](https://marketplace.visualstudio.com/)

**Comment by brunoalr** [comment]
Hi @ghost. As of now gdb-imagewatch is not available as an extension for Visual Code.
However, as long as you are using Linux and gdb as your debugger, if you follow this [step](https://github.com/csantosbh/gdb-imagewatch/blob/master/README.md#loading-pugin) gdb-imagewatch will load whenever you hit a breakpoint.
