### ISSUE TITLE
Solved how to use it in Eclipse IDE(Ubuntu)

### ISSUE THREAD

**Issue by YihaoWEI** [csantosbh/gdb-imagewatch#47]
Now I think I have found the way on how to get the correct set of doing the gdb-imagewatch set in Eclipse: 
Set the **Run->Debug Configuration->Debugger->GDB command file** and input the **/path/to/your/gdb-imagewatch.py** 
Then it may work!

**Comment by csantosbh** [comment]
Great! Thanks for the input!
