### ISSUE TITLE
gdb-imagewatch on remote

### ISSUE THREAD

**Issue by ghost** [csantosbh/gdb-imagewatch#48]
I am using opencv on my remote target and I'd like to use this plugin to help debug with opencv remotely. Nowadays I'm debugging with Eclipse and I'd like to somehow use it and integrate with it so when I am stepping program to see my Mat images - so how how to configure for it?
Thank you.

**Comment by brunoalr** [comment]
gdb-imagewatch must be loaded in the client gdb, you don't have to change anything in the remote/server side :)

To integrate with Eclipse, you can try these steps: https://github.com/csantosbh/gdb-imagewatch/issues/47#issue-388472749 (not tested by @csantosbh or me).

On a system level, you can source gdb-imagewatch.py in a .gdbinit file as described in the Readme file.
