### ISSUE TITLE
works with OpenVX

### ISSUE THREAD

**Issue by peter197321** [csantosbh/gdb-imagewatch#51]
is there any example how it cn work with OpenVX?

**Comment by brunoalr** [comment]
Currently there's no support for it. There's an in-depth explanation on how to add new types [here](https://csantosbh.wordpress.com/2016/10/15/configuring-gdb-imagewatch-to-visualize-custom-buffer-types/) is and [here](https://github.com/csantosbh/gdb-imagewatch/tree/master/resources/giwscripts/giwtypes) you can find some examples.
