### ISSUE TITLE
gdb-imagewatch.pro:80: Unknown replace function: shell_path

### ISSUE THREAD

**Issue by minghuizhou123** [csantosbh/gdb-imagewatch#52]
~/software/gdb-imagewatch/build$ qmake .. BUILD_MODE=release PREFIX=/usr/local
Project MESSAGE: GDB-ImageWatch build mode: release
/software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path
/software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path
software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path
/software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path
/software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path
/software/gdb-imagewatch/gdb-imagewatch.pro:80: Unknown replace function: shell_path

**Comment by brunoalr** [comment]
Please make sure you are using qt version >= 5.
See https://github.com/csantosbh/gdb-imagewatch#ubuntu-1604-manual-installation-with-qtcreator
